name: Android CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    #runs-on: macos-latest
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Restore Gradle cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Run Unit Tests
      run: ./gradlew test

    - name: Run Instrumentation Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 24
        target: default
        arch: x86
        profile: Nexus 6
        script: ./gradlew connectedDebugAndroidTest --stacktrace

    - name: Build Debug with Gradle
      run: ./gradlew assembleDebug
